/**
 * RemyNest brand tokens — the single source of truth for the UI-CHROME color, type,
 * and geometry system, mirrored by tailwind.config.js + app/globals.css. (The former
 * Next.js sage asset routes were retired 2026-07-18 — identity assets are static
 * purple PNGs generated by scripts/generate-brand-assets.mjs.)
 *
 * IDENTITY vs CHROME (authoritative — see CLAUDE.md / docs/brand/brand-guidelines.md):
 *   IDENTITY       = the purple fingerprint-heart-bird mark on every platform surface.
 *   UI CHROME      = sage / sand / gold → the app's interior design system (these tokens).
 *   COMPANION/REMY = purple + gold pendant → the in-app avatar/chat ONLY (kept here
 *                    only so the boundary is explicit; NEVER use on the product brand).
 *   Gold is the shared bridge token between the two systems.
 */

// ---- Product/brand primitives (verbatim from tailwind.config.js) ------------
export const BRAND = {
  sage: "#4F6B5B", // Forest Sage — primary
  sageDeep: "#3E5648",
  sageSoft: "#8FAE8A", // Soft Moss — success / gentle accent
  sand: "#F5F1EA", // Warm Sand — background
  sandDeep: "#E7E0D3", // hairlines / quiet fills
  gold: "#C9A86A", // Soft Gold — accent (FILLS/GRAPHICS only, fails as text)
  goldSoft: "#E3D1A9",
  goldInk: "#7A5E22", // NEW text-grade gold for links/accent-text (AA on light)
  charcoal: "#2F3E34", // text
  charcoalSoft: "#54655B", // secondary text
  charcoalMuted: "#7C887F", // tertiary — decorative ≥18px ONLY (fails as body)
  white: "#FFFFFF",
} as const;

// ---- Companion/Remy character palette (IN-APP ONLY — never on product brand) -
export const REMY = {
  purpleLight: "#8A6BD0",
  purpleDeep: "#5B3E8E",
  pendant: "#E3A24A",
} as const;

// ---- Dark theme (warm charcoal-green — NOT black/blue) -----------------------
export const DARK = {
  bg: "#15201A",
  surface: "#1E2A23",
  surface2: "#26332B",
  text: "#ECE5D8",
  textSoft: "#C2C9BE",
  textMuted: "#94A096",
  primary: "#8FAE8A", // sage-light (takes dark ink)
  accent: "#DBC089", // gold-light (takes dark ink)
  ink: "#15201A", // on-primary / on-accent
  border: "#33423A",
  borderStrong: "#6E7E72",
} as const;

// ---- Type + geometry --------------------------------------------------------
export const FONT = {
  sans: "Inter", // body / UI
  serif: "Fraunces", // display / headings / memory titles
} as const;

export const RADIUS = { lg: "1rem", "4xl": "2rem" } as const;

// ---- Verified WCAG pairings (sRGB, AA = 4.5:1 text / 3:1 large·UI) -----------
// PASS: charcoal/sand 10:1 · charcoal-soft/sand 5.5:1 · sage/sand 5.2:1 ·
//   white/sage 5.86:1 · gold-ink/sand 5.4:1 · charcoal/gold 5.0:1.
// FAIL (never as text): gold/sand 2.0:1 · charcoal-muted/sand 3.3:1 (≥18px only) ·
//   white/gold 2.26:1 (gold buttons take charcoal ink).
