import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "RemyNest",
    short_name: "RemyNest",
    description: "Capture memories and ask Remy about your people, reminders, and life story.",
    start_url: "/",
    display: "standalone",
    background_color: "#F5F1EA",
    theme_color: "#5B3E8E",
    orientation: "portrait",
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // Safe-zone maskable variants (generated by scripts/generate-brand-assets.mjs)
      // so Android/PWA installs render a properly-padded adaptive icon.
      {
        src: "/brand/icons/maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/brand/icons/maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}